In [1]:
import pandas as pd
import numpy as np

In [2]:
postings_df = pd.read_csv("../data/raw/Version_9/job_postings.csv")

postings_df.head()

,job_id,company_id,title,description,max_salary,med_salary,min_salary,pay_period,formatted_work_type,location,...,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,scraped
0,3757940104,553718.0,Hearing Care Provider,Overview\n\nHearingLife is a national hearing ...,NaN,5250.00,NaN,MONTHLY,Full-time,"Little River, SC",...,NaN,Entry level,NaN,1.699090e+12,careers-demant.icims.com,0,FULL_TIME,USD,BASE_SALARY,1699138101
1,3757940025,2192142.0,Shipping & Receiving Associate 2nd shift (Beav...,Metalcraft of Mayville\nMetalcraft of Mayville...,NaN,NaN,NaN,NaN,Full-time,"Beaver Dam, WI",...,NaN,NaN,NaN,1.699080e+12,www.click2apply.net,0,FULL_TIME,NaN,NaN,1699085420
2,3757938019,474443.0,"Manager, Engineering",\nThe TSUBAKI name is synonymous with excellen...,NaN,NaN,NaN,NaN,Full-time,"Bessemer, AL",...,NaN,NaN,Bachelor's Degree in Mechanical Engineering pr...,1.699080e+12,www.click2apply.net,0,FULL_TIME,NaN,NaN,1699085644
3,3757938018,18213359.0,Cook,descriptionTitle\n\n Looking for a great oppor...,NaN,22.27,NaN,HOURLY,Full-time,"Aliso Viejo, CA",...,NaN,Entry level,NaN,1.699080e+12,jobs.apploi.com,0,FULL_TIME,USD,BASE_SALARY,1699087461
4,3757937095,437225.0,Principal Cloud Security Architect (Remote),"Job Summary\nAt iHerb, we are on a mission to ...",275834.0,NaN,205956.0,YEARLY,Full-time,United States,...,NaN,Mid-Senior level,NaN,1.699090e+12,careers.iherb.com,0,FULL_TIME,USD,BASE_SALARY,1699085346

In [3]:
print(postings_df.info())
print(postings_df.describe())
print(postings_df.columns.tolist())
print(postings_df.dtypes)
print(postings_df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33246 entries, 0 to 33245
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      33246 non-null  int64
 1   company_id                  32592 non-null  float64
 2   title                       33246 non-null  object
 3   description                 33245 non-null  object
 4   max_salary                  11111 non-null  float64
 5   med_salary                  2241 non-null   float64
 6   min_salary                  11111 non-null  float64
 7   pay_period                  13352 non-null  object
 8   formatted_work_type         33246 non-null  object
 9   location                    33246 non-null  object
 10  applies                     16238 non-null  float64
 11  original_listed_time        33246 non-null  float64
 12  remote_allowed              4802 non-null   float64
 13  views                       25886 non-null  float64
 14  job_posting_url             33246 non-null  object
 15  application_url             20996 non-null  object
 16  application_type            33246 non-null  object
 17  expiry                      33246 non-null  float64
 18  closed_time                 1172 non-null   float64
 19  formatted_experience_level  24065 non-null  object
 20  skills_desc                 337 non-null    object
 21  listed_time                 33246 non-null  float64
 22  posting_domain              19688 non-null  object
 23  sponsored                   33246 non-null  int64
 24  work_type                   33246 non-null  object
 25  currency                    13352 non-null  object
 26  compensation_type           13352 non-null  object
 27  scraped                     33246 non-null  int64
dtypes: float64(11), int64(3), object(14)
memory usage: 7.1+ MB
None
             job_id    company_id    max_salary     med_salary     min_salary  \
count  3.324600e+04  3.259200e+04  1.111100e+04    2241.000000   11111.000000
mean   3.723675e+09  1.145638e+07  8.880883e+04   32426.170598   62650.128421
std    9.264310e+07  2.391219e+07  8.764506e+04   76860.422528   58732.644143
min    3.958427e+06  1.009000e+03  1.000000e+01       0.000000       7.250000
25%    3.697367e+09  1.840100e+04  5.100000e+01      18.780000      40.945000
50%    3.749345e+09  4.687820e+05  8.392800e+04      29.000000   62128.000000
75%    3.756905e+09  9.222480e+06  1.400000e+05   42746.000000  100000.000000
max    3.757940e+09  1.011741e+08  1.300000e+06  998426.000000  800000.000000

            applies  original_listed_time  remote_allowed         views  \
count  16238.000000          3.324600e+04          4802.0  25886.000000
mean      18.895246          1.695907e+12             1.0     58.339875
std       49.059029          3.163863e+09             0.0    141.253774
min        1.000000          1.686210e+12             1.0      1.000000
25%        2.000000          1.692740e+12             1.0      4.000000
50%        5.000000          1.696910e+12             1.0     16.000000
75%       16.000000          1.699040e+12             1.0     54.000000
max     1615.000000          1.699090e+12             1.0   5656.000000

             expiry   closed_time   listed_time     sponsored       scraped
count  3.324600e+04  1.172000e+03  3.324600e+04  33246.000000  3.324600e+04
mean   1.699525e+12  1.692082e+12  1.696043e+12      0.244150  8.872011e+08
std    4.421979e+09  4.061876e+09  3.134178e+09      0.429588  8.487133e+08
min    1.694270e+12  1.690000e+12  1.691670e+12      0.000000  1.000000e+00
25%    1.695340e+12  1.690000e+12  1.692750e+12      0.000000  1.000000e+00
50%    1.701630e+12  1.690000e+12  1.698960e+12      0.000000  1.698996e+09
75%    1.701640e+12  1.690000e+12  1.699050e+12      0.000000  1.699065e+09
max    1.714680e+12  1.700000e+12  1.699140e+12      1.000000  1.699140e+09
['job_id', 'company_id', 'title', 'description', 'max_salary', 'med_salary', 'min_salary', 'pay_period', 'formatted_work_type', 'location', 'applies', 'original_listed_time', 'remote_allowed', 'views', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'scraped']
job_id                          int64
company_id                    float64
title                          object
description                    object
max_salary                    float64
med_salary                    float64
min_salary                    float64
pay_period                     object
formatted_work_type            object
location                       object
applies                       float64
original_listed_time          float64
remote_allowed                float64
views                         float64
job_posting_url                object
application_url                object
application_type               object
expiry                        float64
closed_time                   float64
formatted_experience_level     object
skills_desc                    object
listed_time                   float64
posting_domain                 object
sponsored                       int64
work_type                      object
currency                       object
compensation_type              object
scraped                         int64
dtype: object
job_id                            0
company_id                      654
title                             0
description                       1
max_salary                    22135
med_salary                    31005
min_salary                    22135
pay_period                    19894
formatted_work_type               0
location                          0
applies                       17008
original_listed_time              0
remote_allowed                28444
views                          7360
job_posting_url                   0
application_url               12250
application_type                  0
expiry                            0
closed_time                   32074
formatted_experience_level     9181
skills_desc                   32909
listed_time                       0
posting_domain                13558
sponsored                         0
work_type                         0
currency                      19894
compensation_type             19894
scraped                           0
dtype: int64

In [4]:
postings_df.shape

(33246, 28)

In [5]:
benefits_df = pd.read_csv("../data/raw/Version_13/benefits.csv")

benefits_df.head()

       job_id  inferred                     type
0  3887473071         0        Medical insurance
1  3887473071         0         Vision insurance
2  3887473071         0         Dental insurance
3  3887473071         0                   401(k)
4  3887473071         0  Student loan assistance

In [6]:
print(benefits_df.info())
print(benefits_df.describe())
print(benefits_df.columns.tolist())
print(benefits_df.dtypes)
print(benefits_df.isnull().sum())
print(benefits_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67943 entries, 0 to 67942
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   job_id    67943 non-null  int64
 1   inferred  67943 non-null  int64
 2   type      67943 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.6+ MB
None
             job_id      inferred
count  6.794300e+04  67943.000000
mean   3.896220e+09      0.594969
std    9.817292e+07      0.490902
min    2.322152e+07      0.000000
25%    3.898161e+09      0.000000
50%    3.902348e+09      1.000000
75%    3.904719e+09      1.000000
max    3.906267e+09      1.000000
['job_id', 'inferred', 'type']
job_id       int64
inferred     int64
type        object
dtype: object
job_id      0
inferred    0
type        0
dtype: int64
(67943, 3)

In [7]:
companies_df = pd.read_csv("../data/raw/Version_13/companies.csv")

companies_df.head()

,company_id,name,description,company_size,state,country,city,zip_code,address,url
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture

In [8]:
print(companies_df.info())
print(companies_df.describe())
print(companies_df.columns.tolist())
print(companies_df.dtypes)
print(companies_df.isnull().sum())
print(companies_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24473 entries, 0 to 24472
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_id    24473 non-null  int64
 1   name          24472 non-null  object
 2   description   24176 non-null  object
 3   company_size  21699 non-null  float64
 4   state         24451 non-null  object
 5   country       24473 non-null  object
 6   city          24472 non-null  object
 7   zip_code      24445 non-null  object
 8   address       24451 non-null  object
 9   url           24473 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.9+ MB
None
         company_id  company_size
count  2.447300e+04  21699.000000
mean   2.052239e+07      3.349233
std    3.165929e+07      1.904503
min    1.009000e+03      1.000000
25%    1.654040e+05      2.000000
50%    2.738154e+06      3.000000
75%    2.624142e+07      5.000000
max    1.034730e+08      7.000000
['company_id', 'name', 'description', 'company_size', 'state', 'country', 'city', 'zip_code', 'address', 'url']
company_id        int64
name             object
description      object
company_size    float64
state            object
country          object
city             object
zip_code         object
address          object
url              object
dtype: object
company_id         0
name               1
description      297
company_size    2774
state             22
country            0
city               1
zip_code          28
address           22
url                0
dtype: int64
(24473, 10)

In [9]:
companies_2_df = pd.read_csv("../data/raw/Version_13/company_industries.csv")

companies_2_df.head(10)

   company_id                        industry
0      391906  Book and Periodical Publishing
1    22292832                    Construction
2       20300                         Banking
3     3570660  Book and Periodical Publishing
4      878353         Staffing and Recruiting
5      729238   IT Services and IT Consulting
6      766849         Staffing and Recruiting
7       12828      Food and Beverage Services
8     2934678   IT Services and IT Consulting
9    15984730   IT Services and IT Consulting

In [10]:
print(companies_2_df.info())
print(companies_2_df.describe())
print(companies_2_df.columns.tolist())
print(companies_2_df.dtypes)
print(companies_2_df.isnull().sum())
print(companies_2_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24375 entries, 0 to 24374
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   company_id  24375 non-null  int64
 1   industry    24375 non-null  object
dtypes: int64(1), object(1)
memory usage: 381.0+ KB
None
         company_id
count  2.437500e+04
mean   2.038566e+07
std    3.158083e+07
min    1.009000e+03
25%    1.652215e+05
50%    2.708302e+06
75%    2.503948e+07
max    1.034730e+08
['company_id', 'industry']
company_id     int64
industry      object
dtype: object
company_id    0
industry      0
dtype: int64
(24375, 2)

In [11]:
companies_3_df = pd.read_csv("../data/raw/Version_13/company_specialities.csv")

companies_3_df.head()

   company_id              speciality
0    22292832      window replacement
1    22292832  patio door replacement
2       20300      Commercial Banking
3       20300          Retail Banking
4       20300                Mortgage

In [12]:

print(companies_3_df.info())
print(companies_3_df.describe())
print(companies_3_df.columns.tolist())
print(companies_3_df.dtypes)
print(companies_3_df.isnull().sum())
print(companies_3_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169387 entries, 0 to 169386
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   company_id  169387 non-null  int64
 1   speciality  169387 non-null  object
dtypes: int64(1), object(1)
memory usage: 2.6+ MB
None
         company_id
count  1.693870e+05
mean   1.258875e+07
std    2.451128e+07
min    1.009000e+03
25%    1.103290e+05
50%    1.346497e+06
75%    1.067675e+07
max    1.034588e+08
['company_id', 'speciality']
company_id     int64
speciality    object
dtype: object
company_id    0
speciality    0
dtype: int64
(169387, 2)

In [13]:
employee_df = pd.read_csv("../data/raw/Version_13/employee_counts.csv")

employee_df.head()

   company_id  employee_count  follower_count  time_recorded
0      391906             186           32508     1712346173
1    22292832             311            4471     1712346173
2       20300            1053            6554     1712346173
3     3570660             383           35241     1712346173
4      878353              52           26397     1712346173

In [14]:
print(employee_df.info())
print(employee_df.describe())
print(employee_df.columns.tolist())
print(employee_df.dtypes)
print(employee_df.isnull().sum())
print(employee_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35787 entries, 0 to 35786
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   company_id      35787 non-null  int64
 1   employee_count  35787 non-null  int64
 2   follower_count  35787 non-null  int64
 3   time_recorded   35787 non-null  int64
dtypes: int64(4)
memory usage: 1.1 MB
None
         company_id  employee_count  follower_count  time_recorded
count  3.578700e+04    35787.000000    3.578700e+04   3.578700e+04
mean   1.668254e+07     6715.874256    2.012616e+05   1.713163e+09
std    2.924722e+07    29400.984643    1.114733e+06   3.990869e+05
min    1.009000e+03        0.000000    0.000000e+00   1.712346e+09
25%    6.059650e+04       56.000000    2.738000e+03   1.712861e+09
50%    1.339209e+06      418.000000    1.617800e+04   1.713393e+09
75%    1.544092e+07     2945.000000    7.412950e+04   1.713472e+09
max    1.034730e+08   751125.000000    3.270284e+07   1.713573e+09
['company_id', 'employee_count', 'follower_count', 'time_recorded']
company_id        int64
employee_count    int64
follower_count    int64
time_recorded     int64
dtype: object
company_id        0
employee_count    0
follower_count    0
time_recorded     0
dtype: int64
(35787, 4)

In [15]:
industries_df = pd.read_csv("../data/raw/Version_13/industries.csv")

industries_df.head()

   industry_id                         industry_name
0            1       Defense and Space Manufacturing
1            3       Computer Hardware Manufacturing
2            4                  Software Development
3            5          Computer Networking Products
4            6  Technology, Information and Internet

In [16]:

print(industries_df.info())
print(industries_df.describe())
print(industries_df.columns.tolist())
print(industries_df.dtypes)
print(industries_df.isnull().sum())
print(industries_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   industry_id    422 non-null    int64
 1   industry_name  388 non-null    object
dtypes: int64(1), object(1)
memory usage: 6.7+ KB
None
       industry_id
count   422.000000
mean   1342.305687
std    1212.022551
min       1.000000
25%     108.250000
50%    1161.500000
75%    2279.500000
max    3253.000000
['industry_id', 'industry_name']
industry_id       int64
industry_name    object
dtype: object
industry_id       0
industry_name    34
dtype: int64
(422, 2)

In [17]:
job_1_df = pd.read_csv("../data/raw/Version_13/job_industries.csv")

job_1_df.head()

       job_id  industry_id
0  3884428798           82
1  3887473071           48
2  3887465684           41
3  3887467939           82
4  3887467939           80

In [18]:

print(job_1_df.info())
print(job_1_df.describe())
print(job_1_df.columns.tolist())
print(job_1_df.dtypes)
print(job_1_df.isnull().sum())
print(job_1_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164808 entries, 0 to 164807
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   job_id       164808 non-null  int64
 1   industry_id  164808 non-null  int64
dtypes: int64(2)
memory usage: 2.5 MB
None
             job_id    industry_id
count  1.648080e+05  164808.000000
mean   3.897074e+09     196.155284
std    7.624930e+07     594.230895
min    9.217160e+05       1.000000
25%    3.894876e+09      17.000000
50%    3.902342e+09      44.000000
75%    3.904719e+09      96.000000
max    3.906267e+09    3253.000000
['job_id', 'industry_id']
job_id         int64
industry_id    int64
dtype: object
job_id         0
industry_id    0
dtype: int64
(164808, 2)

In [19]:
job_2_df = pd.read_csv("../data/raw/Version_13/job_skills.csv")

job_2_df.head()

       job_id skill_abr
0  3884428798      MRKT
1  3884428798        PR
2  3884428798       WRT
3  3887473071      SALE
4  3887465684       FIN

In [20]:

print(job_2_df.info())
print(job_2_df.describe())
print(job_2_df.columns.tolist())
print(job_2_df.dtypes)
print(job_2_df.isnull().sum())
print(job_2_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213768 entries, 0 to 213767
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   job_id     213768 non-null  int64
 1   skill_abr  213768 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.3+ MB

None
             job_id
count  2.137680e+05
mean   3.896849e+09
std    7.834902e+07
min    9.217160e+05
25%    3.894661e+09
50%    3.902323e+09
75%    3.904715e+09
max    3.906267e+09
['job_id', 'skill_abr']
job_id        int64
skill_abr    object
dtype: object
job_id       0
skill_abr    0
dtype: int64
(213768, 2)

In [21]:
salaries_df = pd.read_csv("../data/raw/Version_13/salaries.csv")

salaries_df.head()

,salary_id,job_id,max_salary,med_salary,min_salary,pay_period,currency,compensation_type
0,1,3884428798,NaN,20.0,NaN,HOURLY,USD,BASE_SALARY
1,2,3887470552,25.0,NaN,23.0,HOURLY,USD,BASE_SALARY
2,3,3884431523,120000.0,NaN,100000.0,YEARLY,USD,BASE_SALARY
3,4,3884911725,200000.0,NaN,10000.0,YEARLY,USD,BASE_SALARY
4,5,3887473220,35.0,NaN,33.0,HOURLY,USD,BASE_SALARY

In [22]:

print(salaries_df.info())
print(salaries_df.describe())
print(salaries_df.columns.tolist())
print(salaries_df.dtypes)
print(salaries_df.isnull().sum())
print(salaries_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40785 entries, 0 to 40784
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   salary_id          40785 non-null  int64
 1   job_id             40785 non-null  int64
 2   max_salary         33947 non-null  float64
 3   med_salary         6838 non-null   float64
 4   min_salary         33947 non-null  float64
 5   pay_period         40785 non-null  object
 6   currency           40785 non-null  object
 7   compensation_type  40785 non-null  object
dtypes: float64(3), int64(2), object(3)
memory usage: 2.5+ MB
None
          salary_id        job_id    max_salary     med_salary    min_salary
count  40785.000000  4.078500e+04  3.394700e+04    6838.000000  3.394700e+04
mean   20393.000000  3.895564e+09  9.620987e+04   21370.298197  6.508541e+04
std    11773.759701  9.496672e+07  6.587373e+05   51338.564166  4.650612e+05
min        1.000000  9.217160e+05  1.000000e+00       0.000000  1.000000e+00
25%    10197.000000  3.894608e+09  5.000000e+01      18.500000  3.900000e+01
50%    20393.000000  3.901980e+09  8.500000e+04      25.000000  6.230000e+04
75%    30589.000000  3.904576e+09  1.425000e+05    2207.000000  1.000000e+05
max    40785.000000  3.906267e+09  1.200000e+08  750000.000000  8.500000e+07
['salary_id', 'job_id', 'max_salary', 'med_salary', 'min_salary', 'pay_period', 'currency', 'compensation_type']
salary_id              int64
job_id                 int64
max_salary           float64
med_salary           float64
min_salary           float64
pay_period            object
currency              object
compensation_type     object
dtype: object
salary_id                0
job_id                   0
max_salary            6838
med_salary           33947
min_salary            6838
pay_period               0
currency                 0
compensation_type        0
dtype: int64
(40785, 8)

In [23]:
skills_df = pd.read_csv("../data/raw/Version_13/skills.csv")

skills_df.head()

  skill_abr          skill_name
0       ART        Art/Creative
1      DSGN              Design
2      ADVR         Advertising
3      PRDM  Product Management
4      DIST        Distribution

In [24]:

print(skills_df.info())
print(skills_df.describe())
print(skills_df.columns.tolist())
print(skills_df.dtypes)
print(skills_df.isnull().sum())
print(skills_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   skill_abr   35 non-null     object
 1   skill_name  35 non-null     object
dtypes: object(2)
memory usage: 692.0+ bytes
None
       skill_abr    skill_name
count         35            35
unique        35            35
top          ART  Art/Creative
freq           1             1
['skill_abr', 'skill_name']
skill_abr     object
skill_name    object
dtype: object
skill_abr     0
skill_name    0
dtype: int64
(35, 2)